baseurl = "https://ben-stelling.netlify.com/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Ben Stelling"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "A squiggle trying to analyze data."
  logo = "img/headshot.jpg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "img/odontella.jpg"
  desc = "Triangle"
  position = "center top"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  #name = "Ben Stelling"
  website = "benstelling.com"
  email = "plankton.doctor@gmail.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "Ben-stelling"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "Plankton_doctor"
  #reddit = "username"
  linkedin = "ben-stelling-12268579/"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  instagram = "dr._plankton"
  youtube = "Dr. Plankton" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    parent = "blog"
    name = "Phytoplankton Ecology"
    url = "post/2017-03-07-bigimg-sample"
    weight = 1
    
[[menu.main]]
    parent = "blog"
    name = "Chemistry/Molecular Biology"
    url = "post/2017-03-07-bigimg-sample"
    weight = 3
    
[[menu.main]]
    parent = "blog"
    name = "Remote Sensing"
    url = "post/2017-03-07-bigimg-sample"
    weight = 4
    
[[menu.main]]
    parent = "blog"
    name = "Handling Data with R"
    url = "post/2017-03-07-bigimg-sample"
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "/post/Resume_2019.pdf"
    weight = 3
    
#[[menu.main]]
#    name = "About"
#    url = "post/Resume_2019"
#    weight = 3

[[menu.main]]
    identifier = "samples"
    name = "Samples"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Big Image Sample"
    url = "post/2017-03-07-bigimg-sample"
    weight = 1

[[menu.main]]
    parent = "samples"
    name = "Math Sample"
    url = "post/2017-03-05-math-sample"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Code Sample"
    url = "post/2016-03-08-code-sample"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
